asr:
  #url: "https://twcc-speech.thebarkingdog.tw/api/v1/asr"
  url: "http://127.0.0.1:8000/asr"
  model_size: "medium" 
  concurrent_users: 5
  audio_file: "car.mp3"

tts:
  url: "http://127.0.0.1:8000/tts"
  text: "您好~我是AI助理，很高興為您服務！"
  concurrent_users: 5  

llm:
  url: "http://127.0.0.1:11434/api/generate"
  model: "mistral-nemo:latest"
  prompt: "請用繁體中文回答：什麼是人工智能？"
  concurrent_users: 5

  
